server:
  port: 7070
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=employee;trustServerCertificate=true;
    username: Iyyappan
    password: PzqM24#03$
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none



